otcdocstheme/theme/otcdocs/static/js/docs.js

Fixed Tables

---

otcdocstheme/theme/otcdocs/static/js/docs.js

Drop ansible collection workaround

---

otcdocstheme/theme/otcdocs/header.html
releasenotes/notes/add-project-links-ff3e9377417a5c10.yaml

in the header add links to SW docs and releasenotes.

Add links between SW projects

---

otcdocstheme/theme/otcdocs/static/css/combined.css
releasenotes/notes/fix-table-09c4e5eaf38be8c0.yaml

Copy css table part from openstackdocstheme

Add table border color

---

otcdocstheme/theme/otcdocs/footer.html

in order to keep legal happy let us keep the links we have currently at
all out other pages.

Restore original footer links

---

doc/requirements.txt
doc/source/conf.py
otcdocstheme/theme/otcdocs/header.html
otcdocstheme/theme/otcdocs/layout.html
otcdocstheme/theme/otcdocs/static/css/otcdocstheme.css
otcdocstheme/theme/otcdocs/theme.conf

- Switch to bootstrap5
- add rn and fix some stuff
- propose offcanvas based topnav
- implement regular navbar

navbar pulldown

---

otcdocstheme/theme/otcdocs/css.html
otcdocstheme/theme/otcdocs/layout.html
otcdocstheme/theme/otcdocs/localtoc.html

Under some conditions toc sidebar is not displayed. Fix this by dropping
most likely initially wrong condition part.

Fix display_toc if condition

---

otcdocstheme/theme/otcdocs/static/css/otcdocstheme.css

Instead of placing caption bottom move it to top

Put table caption above the table

---

otcdocstheme/theme/otcdocs/localtoc.html
otcdocstheme/theme/otcdocs/sidebartoc.html
otcdocstheme/theme/otcdocs/static/css/otcdocstheme.css
otcdocstheme/theme/otcdocs/static/js/search.js

closes #62 
No Modal, but also works

Hide sidebars when searching and pressing enter

---

otcdocstheme/theme/otcdocs/css.html
otcdocstheme/theme/otcdocs/script_footer.html

- add font preloading
- do not load unused js

Increase page performance

---

doc/source/conf.py
otcdocstheme/theme/otcdocs/static/js/docs.js

- fix pdf file name
- fix pdf path calculation

Fix pdf link

---

otcdocstheme/theme/otcdocs/static/js/docs.js

Open Links in new Tab

---

doc/source/index.rst
otcdocstheme/theme/otcdocs/footer.html
otcdocstheme/theme/otcdocs/header.html
otcdocstheme/theme/otcdocs/layout.html
otcdocstheme/theme/otcdocs/sidebartoc.html
otcdocstheme/theme/otcdocs/theme.conf
releasenotes/notes/various_updates-8f7ae9e3c2d58d2d.yaml

- add disable/display options
- reorg layout to better match sphinx layout

Various fixes

---

otcdocstheme/theme/otcdocs/static/js/search.js

Closing search dropdown when clicking anywhere else

---

otcdocstheme/theme/otcdocs/static/js/search.js

Related to https://github.com/opentelekomcloud-docs/docsportal/pull/26 (needs to be merged first)
closes #88

Added checks for docsportal

---

otcdocstheme/theme/otcdocs/static/js/search.js

closes #114 
We need to first test whether all search results still make sense or whether search quality degraded with that change.

Find results for partial words

---

doc/source/conf.py
otcdocstheme/ext.py
otcdocstheme/theme/otcdocs/header.html
otcdocstheme/theme/otcdocs/theme.conf

Added configurable logo URL

---

doc/source/conf.py
otcdocstheme/ext.py
otcdocstheme/theme/otcdocs/localtoc.html

Added option for changing main URL for repo links

---

otcdocstheme/theme/otcdocs/header.html

- add container services link
- rename data analysis to big data and data analysis

Fix header links

---

otcdocstheme/theme/otcdocs/static/js/search.js

Please test whether this query provides better results or not. Especially also with multiple words.

Changed Search Query

---

doc/source/conf.py
otcdocstheme/ext.py
otcdocstheme/theme/otcdocs/script_footer.html
otcdocstheme/theme/otcdocs/static/js/search.js
releasenotes/source/conf.py

This will break current search if no parameter is specified. Don't merge till rollout on GitHub has happened.

Added search option for swiss

---

doc/source/conf.py
otcdocstheme/ext.py
otcdocstheme/theme/otcdocs/script_footer.html
otcdocstheme/theme/otcdocs/static/js/search.js

The Default is: `https://opensearch.eco.tsi-dev.otc-service.com/`

Added Option to specify OpenSearch URL

---

otcdocstheme/theme/otcdocs/static/css/otcdocstheme.css

Fix scrollbar on long sidebar

---

otcdocstheme/ext.py
otcdocstheme/theme/otcdocs/header.html

fix issue #186

---

otcdocstheme/theme/otcdocs/static/css/otcdocstheme.css

fix issue #187

---

otcdocstheme/theme/otcdocs/header.html

Switched icons

---

otcdocstheme/theme/otcdocs/header.html

adjust all href values to point **/architecture-center/blueprints** or **/architecture-center/caf**

adjust main-nav and mobile-nav hrefs to new blueprints and caf structure

---

otcdocstheme/theme/otcdocs/layout.html
otcdocstheme/theme/otcdocs/sidebartoc.html

closes https://github.com/opentelekomcloud/otcdocstheme/issues/212

Update Breadcrumbs to include links to SBV

---

otcdocstheme/theme/otcdocs/header.html
otcdocstheme/theme/otcdocs/static/css/otcdocstheme.css

closes https://github.com/opentelekomcloud/otcdocstheme/issues/227

Fix padding on Navbar subheadings

---

otcdocstheme/theme/otcdocs/header.html

fixes https://github.com/opentelekomcloud-docs/docsportal/issues/217

Removed RTS
